/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Payment model module.
 * @module model/Payment
 * @version 1.0.0
 */
class Payment {
    /**
     * Constructs a new <code>Payment</code>.
     * @alias module:model/Payment
     * @param firstName {String} 
     * @param lastName {String} 
     * @param email {String} 
     * @param phoneNumber {Number} 
     * @param shFirstName {String} 
     * @param shLastName {String} 
     * @param shEmail {String} 
     * @param shPhoneNumber {Number} 
     * @param shAddress {String} 
     * @param shZipCode {Number} 
     * @param notes {String} 
     * @param paymentMethod {String} 
     */
    constructor(firstName, lastName, email, phoneNumber, shFirstName, shLastName, shEmail, shPhoneNumber, shAddress, shZipCode, notes, paymentMethod) { 
        
        Payment.initialize(this, firstName, lastName, email, phoneNumber, shFirstName, shLastName, shEmail, shPhoneNumber, shAddress, shZipCode, notes, paymentMethod);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstName, lastName, email, phoneNumber, shFirstName, shLastName, shEmail, shPhoneNumber, shAddress, shZipCode, notes, paymentMethod) { 
        obj['FirstName'] = firstName;
        obj['LastName'] = lastName;
        obj['Email'] = email;
        obj['PhoneNumber'] = phoneNumber;
        obj['ShFirstName'] = shFirstName;
        obj['ShLastName'] = shLastName;
        obj['ShEmail'] = shEmail;
        obj['ShPhoneNumber'] = shPhoneNumber;
        obj['ShAddress'] = shAddress;
        obj['ShZipCode'] = shZipCode;
        obj['Notes'] = notes;
        obj['PaymentMethod'] = paymentMethod;
    }

    /**
     * Constructs a <code>Payment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Payment} obj Optional instance to populate.
     * @return {module:model/Payment} The populated <code>Payment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Payment();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('FirstName')) {
                obj['FirstName'] = ApiClient.convertToType(data['FirstName'], 'String');
            }
            if (data.hasOwnProperty('LastName')) {
                obj['LastName'] = ApiClient.convertToType(data['LastName'], 'String');
            }
            if (data.hasOwnProperty('Email')) {
                obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
            }
            if (data.hasOwnProperty('PhoneNumber')) {
                obj['PhoneNumber'] = ApiClient.convertToType(data['PhoneNumber'], 'Number');
            }
            if (data.hasOwnProperty('ShFirstName')) {
                obj['ShFirstName'] = ApiClient.convertToType(data['ShFirstName'], 'String');
            }
            if (data.hasOwnProperty('ShLastName')) {
                obj['ShLastName'] = ApiClient.convertToType(data['ShLastName'], 'String');
            }
            if (data.hasOwnProperty('ShEmail')) {
                obj['ShEmail'] = ApiClient.convertToType(data['ShEmail'], 'String');
            }
            if (data.hasOwnProperty('ShPhoneNumber')) {
                obj['ShPhoneNumber'] = ApiClient.convertToType(data['ShPhoneNumber'], 'Number');
            }
            if (data.hasOwnProperty('ShAddress')) {
                obj['ShAddress'] = ApiClient.convertToType(data['ShAddress'], 'String');
            }
            if (data.hasOwnProperty('ShZipCode')) {
                obj['ShZipCode'] = ApiClient.convertToType(data['ShZipCode'], 'Number');
            }
            if (data.hasOwnProperty('Notes')) {
                obj['Notes'] = ApiClient.convertToType(data['Notes'], 'String');
            }
            if (data.hasOwnProperty('PaymentMethod')) {
                obj['PaymentMethod'] = ApiClient.convertToType(data['PaymentMethod'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Payment.prototype['_id'] = undefined;

/**
 * @member {String} FirstName
 */
Payment.prototype['FirstName'] = undefined;

/**
 * @member {String} LastName
 */
Payment.prototype['LastName'] = undefined;

/**
 * @member {String} Email
 */
Payment.prototype['Email'] = undefined;

/**
 * @member {Number} PhoneNumber
 */
Payment.prototype['PhoneNumber'] = undefined;

/**
 * @member {String} ShFirstName
 */
Payment.prototype['ShFirstName'] = undefined;

/**
 * @member {String} ShLastName
 */
Payment.prototype['ShLastName'] = undefined;

/**
 * @member {String} ShEmail
 */
Payment.prototype['ShEmail'] = undefined;

/**
 * @member {Number} ShPhoneNumber
 */
Payment.prototype['ShPhoneNumber'] = undefined;

/**
 * @member {String} ShAddress
 */
Payment.prototype['ShAddress'] = undefined;

/**
 * @member {Number} ShZipCode
 */
Payment.prototype['ShZipCode'] = undefined;

/**
 * @member {String} Notes
 */
Payment.prototype['Notes'] = undefined;

/**
 * @member {String} PaymentMethod
 */
Payment.prototype['PaymentMethod'] = undefined;






export default Payment;

