/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Rental model module.
 * @module model/Rental
 * @version 1.0.0
 */
class Rental {
    /**
     * Constructs a new <code>Rental</code>.
     * @alias module:model/Rental
     * @param vehicleType {String} 
     * @param rentStart {String} 
     * @param rentEnd {String} 
     */
    constructor(vehicleType, rentStart, rentEnd) { 
        
        Rental.initialize(this, vehicleType, rentStart, rentEnd);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, vehicleType, rentStart, rentEnd) { 
        obj['VehicleType'] = vehicleType;
        obj['RentStart'] = rentStart;
        obj['RentEnd'] = rentEnd;
    }

    /**
     * Constructs a <code>Rental</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Rental} obj Optional instance to populate.
     * @return {module:model/Rental} The populated <code>Rental</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Rental();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('VehicleType')) {
                obj['VehicleType'] = ApiClient.convertToType(data['VehicleType'], 'String');
            }
            if (data.hasOwnProperty('RentStart')) {
                obj['RentStart'] = ApiClient.convertToType(data['RentStart'], 'String');
            }
            if (data.hasOwnProperty('RentEnd')) {
                obj['RentEnd'] = ApiClient.convertToType(data['RentEnd'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Rental.prototype['_id'] = undefined;

/**
 * @member {String} VehicleType
 */
Rental.prototype['VehicleType'] = undefined;

/**
 * @member {String} RentStart
 */
Rental.prototype['RentStart'] = undefined;

/**
 * @member {String} RentEnd
 */
Rental.prototype['RentEnd'] = undefined;






export default Rental;

